apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kuburendertron.com
    http:
      paths:
      - path: /testpath2
        pathType: Prefix
        backend:
          service:
            name: ingress-nginx
            port:
              number: 80
        