apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendertron-deployment
  labels:
    app: nginx
spec:
#the replicas allow self-healing
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: rendertron-kube
        image: yomofo2s/rendertron:latest
        ports:
        - containerPort: 80
